### ISSUE TITLE
Windows Running Error

### ISSUE THREAD

**Issue by memory125** [jamesaud/VENoM-Docker#2]
When I running this project on Windows, it failed with the following error:
docker-compose up
Starting venom-docker_client_1          ... done
Starting venom-docker_server-database_1 ... done
Starting venom-docker_server_1          ... done
Attaching to venom-docker_server-database_1, venom-docker_client_1, venom-docker_server_1
server-database_1  | 2018-09-20T08:12:22.053+0000 I CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
server-database_1  | 2018-09-20T08:12:22.058+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=e7c989cbb919
server-database_1  | 2018-09-20T08:12:22.058+0000 I CONTROL  [initandlisten] db version v4.0.2
server-database_1  | 2018-09-20T08:12:22.058+0000 I CONTROL  [initandlisten] git version: fc1573ba18aee42f97a3bb13b67af7d837826b47
server-database_1  | 2018-09-20T08:12:22.058+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
server-database_1  | 2018-09-20T08:12:22.058+0000 I CONTROL  [initandlisten] allocator: tcmalloc
server-database_1  | 2018-09-20T08:12:22.058+0000 I CONTROL  [initandlisten] modules: none
server-database_1  | 2018-09-20T08:12:22.058+0000 I CONTROL  [initandlisten] build environment:
server-database_1  | 2018-09-20T08:12:22.058+0000 I CONTROL  [initandlisten]     distmod: ubuntu1604
server-database_1  | 2018-09-20T08:12:22.058+0000 I CONTROL  [initandlisten]     distarch: x86_64
server-database_1  | 2018-09-20T08:12:22.058+0000 I CONTROL  [initandlisten]     target_arch: x86_64
server-database_1  | 2018-09-20T08:12:22.058+0000 I CONTROL  [initandlisten] options: { net: { bindIpAll: true } }
server-database_1  | 2018-09-20T08:12:22.067+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=478M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
server-database_1  | 2018-09-20T08:12:22.679+0000 E STORAGE  [initandlisten] WiredTiger error (1) [1537431142:679908][1:0x7f3cf3e73a00], connection: __posix_open_file, 711: /data/db/WiredTiger.wt: handle-open: open: Operation not permitted Raw: [1537431142:679908][1:0x7f3cf3e73a00], connection: __posix_open_file, 711: /data/db/WiredTiger.wt: handle-open: open: Operation not permitted
server-database_1  | 2018-09-20T08:12:22.708+0000 E STORAGE  [initandlisten] WiredTiger error (17) [1537431142:708359][1:0x7f3cf3e73a00], connection: __posix_open_file, 711: /data/db/WiredTiger.wt: handle-open: open: File exists Raw: [1537431142:708359][1:0x7f3cf3e73a00], connection: __posix_open_file, 711: /data/db/WiredTiger.wt: handle-open: open: File exists
server-database_1  | 2018-09-20T08:12:22.711+0000 I STORAGE  [initandlisten] WiredTiger message unexpected file WiredTiger.wt found, renamed to WiredTiger.wt.1
server-database_1  | 2018-09-20T08:12:22.712+0000 E STORAGE  [initandlisten] WiredTiger error (1) [1537431142:712793][1:0x7f3cf3e73a00], connection: __posix_open_file, 711: /data/db/WiredTiger.wt: handle-open: open: Operation not permitted Raw: [1537431142:712793][1:0x7f3cf3e73a00], connection: __posix_open_file, 711: /data/db/WiredTiger.wt: handle-open: open: Operation not permitted
server-database_1  | 2018-09-20T08:12:22.732+0000 E STORAGE  [initandlisten] WiredTiger error (17) [1537431142:732617][1:0x7f3cf3e73a00], connection: __posix_open_file, 711: /data/db/WiredTiger.wt: handle-open: open: File exists Raw: [1537431142:732617][1:0x7f3cf3e73a00], connection: __posix_open_file, 711: /data/db/WiredTiger.wt: handle-open: open: File exists
server-database_1  | 2018-09-20T08:12:22.735+0000 I STORAGE  [initandlisten] WiredTiger message unexpected file WiredTiger.wt found, renamed to WiredTiger.wt.2
server-database_1  | 2018-09-20T08:12:22.737+0000 E STORAGE  [initandlisten] WiredTiger error (1) [1537431142:737245][1:0x7f3cf3e73a00], connection: __posix_open_file, 711: /data/db/WiredTiger.wt: handle-open: open: Operation not permitted Raw: [1537431142:737245][1:0x7f3cf3e73a00], connection: __posix_open_file, 711: /data/db/WiredTiger.wt: handle-open: open: Operation not permitted
server-database_1  | 2018-09-20T08:12:22.739+0000 F STORAGE  [initandlisten] Failed to start up WiredTiger under any compatibility version.
server-database_1  | 2018-09-20T08:12:22.739+0000 F STORAGE  [initandlisten] 1: Operation not permitted
server-database_1  | 2018-09-20T08:12:22.739+0000 F -        [initandlisten] Fatal Assertion 28595 at src/mongo/db/storage/wiredtiger/wiredtiger_kv_engine.cpp 196
server-database_1  | 2018-09-20T08:12:22.739+0000 F -        [initandlisten]
server-database_1  |
server-database_1  | ***aborting after fassert() failure
server-database_1  |
server-database_1  |
client_1           | standard_init_linux.go:190: exec user process caused "no such file or directory"
server_1           | standard_init_linux.go:190: exec user process caused "no such file or directory"
venom-docker_client_1 exited with code 1
venom-docker_server-database_1 exited with code 14
venom-docker_server_1 exited with code 1

Have your tried it on Windows 10 platform? Or any suggestion, please share it. 
Much appreciated.

**Comment by memory125** [comment]
It works well on mac.

**Comment by WeetA34** [comment]
I have a similar issue with mongodb helm chart on docker Windows.
i guess it's the same issue as with virtualbox: https://www.virtualbox.org/ticket/819

https://docs.mongodb.com/manual/administration/production-notes/#fsync-on-directories
"MongoDB requires a filesystem that supports fsync() on directories. For example, HGFS and Virtual Box’s shared folders do not support this operation."

**Comment by jamesaud** [comment]
I think this is not an issue specific to this project, but perhaps your specific setup - so I'm going to close it. Let me know if this is not the case
